# ---- BUILD STAGE ----
FROM node:18-slim AS builder

# Dependencias necesarias para Strapi, sharp, vips, etc.
RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    pkg-config \
    libvips-dev \
    git \
    && apt-get clean

WORKDIR /app

# Copiamos package.json y yarn.lock
COPY package*.json yarn.lock* ./

# Instalamos dependencias
RUN if [ -f yarn.lock ]; then yarn install --frozen-lockfile --network-concurrency 1; \
    else npm install --no-audit --prefer-offline --progress=false; \
    fi

# Copiamos el resto del código
COPY . .

# ---- ARGs para build ----
ARG AZURE_ACCOUNT_NAME
ARG AZURE_ACCOUNT_KEY
ARG AZURE_CONTAINER_NAME
ARG AZURE_DEFAULT_PATH
ARG AZURE_REMOVE_CN

ARG DATABASE_CLIENT
ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_NAME
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG DATABASE_SSL

ARG ADMIN_STRAPI_JWT_SECRET
ARG STRAPI_APP_KEYS
ARG STRAPI_API_TOKEN_SALT
ARG STRAPI_JWT_SECRET

# ---- ENV temporales para build ----
ENV AZURE_ACCOUNT_NAME=$AZURE_ACCOUNT_NAME
ENV AZURE_ACCOUNT_KEY=$AZURE_ACCOUNT_KEY
ENV AZURE_CONTAINER_NAME=$AZURE_CONTAINER_NAME
ENV AZURE_DEFAULT_PATH=$AZURE_DEFAULT_PATH
ENV AZURE_REMOVE_CN=$AZURE_REMOVE_CN

ENV DATABASE_CLIENT=$DATABASE_CLIENT
ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_PORT=$DATABASE_PORT
ENV DATABASE_NAME=$DATABASE_NAME
ENV DATABASE_USERNAME=$DATABASE_USERNAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_SSL=$DATABASE_SSL

ENV ADMIN_STRAPI_JWT_SECRET=$ADMIN_STRAPI_JWT_SECRET
ENV STRAPI_APP_KEYS=$STRAPI_APP_KEYS
ENV STRAPI_API_TOKEN_SALT=$STRAPI_API_TOKEN_SALT
ENV STRAPI_JWT_SECRET=$STRAPI_JWT_SECRET

# Build del admin panel
RUN yarn build

# ---- RUNTIME STAGE ----
FROM node:18-slim

# Dependencias runtime
RUN apt-get update && apt-get install -y \
    libvips-dev \
    && apt-get clean

WORKDIR /app
ENV NODE_ENV=development
EXPOSE 1337

# Copiamos todo desde build stage
COPY --from=builder /app /app

# ---- ENV runtime (sobrescribe build args si es necesario) ----
ENV AZURE_ACCOUNT_NAME=$AZURE_ACCOUNT_NAME
ENV AZURE_ACCOUNT_KEY=$AZURE_ACCOUNT_KEY
ENV AZURE_CONTAINER_NAME=$AZURE_CONTAINER_NAME
ENV AZURE_DEFAULT_PATH=$AZURE_DEFAULT_PATH
ENV AZURE_REMOVE_CN=$AZURE_REMOVE_CN

ENV DATABASE_CLIENT=$DATABASE_CLIENT
ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_PORT=$DATABASE_PORT
ENV DATABASE_NAME=$DATABASE_NAME
ENV DATABASE_USERNAME=$DATABASE_USERNAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_SSL=$DATABASE_SSL

ENV ADMIN_STRAPI_JWT_SECRET=$ADMIN_STRAPI_JWT_SECRET
ENV STRAPI_APP_KEYS=$STRAPI_APP_KEYS
ENV STRAPI_API_TOKEN_SALT=$STRAPI_API_TOKEN_SALT
ENV STRAPI_JWT_SECRET=$STRAPI_JWT_SECRET

# Usuario no root
RUN useradd -m strapi
USER strapi

# Comando por defecto
CMD ["npm", "run", "start"]
