name: CMS Build and Deploy #

on:
  push:
    branches:
      - staging   # luego la cambiamos a main

env:
  IMAGE_NAME: strapi-ctrl365
  CONTAINER_APP_NAME: strapi-ctrl365
  RESOURCE_GROUP: WebCtrl365-staging
  REGISTRY: ${{ secrets.STRAPI_LOGIN_SERVER }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Build Number
        id: buildnumber
        run: echo "BUILD_NUM=$(date +%s)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .

          docker tag $REGISTRY/$IMAGE_NAME:${{ github.sha }} \
            $REGISTRY/$IMAGE_NAME:latest

          docker tag $REGISTRY/$IMAGE_NAME:${{ github.sha }} \
            $REGISTRY/$IMAGE_NAME:1.0.${BUILD_NUM}

      - name: Push Docker Image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:1.0.${BUILD_NUM}

      - name: Deploy to Container App
        run: |
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $REGISTRY/$IMAGE_NAME:${{ github.sha }}
