name: Trigger auto deployment for strapi-ctrl365

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ staging ]
    paths:
    - '**'
    - '.github/workflows/strapi-ctrl365-AutoDeployTrigger-b7434043-d982-470e-993f-6081f1be7cb7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.STRAPICTRL365_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.STRAPICTRL365_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.STRAPICTRL365_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: stagingctrl365com.azurecr.io
          registryUsername: ${{ secrets.STRAPICTRL365_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.STRAPICTRL365_REGISTRY_PASSWORD }}
          containerAppName: strapi-ctrl365
          resourceGroup: WebCtrl365-staging
          imageToBuild: stagingctrl365com.azurecr.io/strapi-ctrl365:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


